/**
 * vmapWriter.js - serialize a generated map into the .vmap archive format.
 *
 * .vmap is a zip of JSON entries:
 *   header.json            - size, players, allow-lists, victory strings
 *   <level>_terrain.json   - 2D array of tile codes "<shortId><view><flip>"
 *   objects.json           - [{instanceName, l, subtype, template:{animation,mask}, type, x, y}]
 *
 * Tile code shape, checked against MapFormatJson.cpp:
 *   <2-char terrain shortIdentifier><view digits><flip char>
 *   then optionally <2-char road shortIdentifier><dir digits><flip char>
 *   then optionally <2-char river shortIdentifier><dir digits><flip char>
 * The reader decides road versus river by trying the road table first and
 * falling back to the river table, so the two-char code has to be one it knows.
 */
'use strict';

const { writeZip } = require('./zipWriter');

/**
 * Flip characters, in the engine's order (MapFormatJson.cpp:235,
 * `flipCodes = {'_', '-', '|', '+'}`): none, horizontal, vertical, both.
 *
 * The fourth entry used to be '/'. Nothing broke only because index 0 is the
 * only one that was ever written. An unknown flip character makes
 * `vstd::find_pos` return -1 and `readTerrainTile` throw, and the catch around
 * it only writes a log line, so the tile would have been left at whatever it
 * was with no visible error.
 */
const FLIP_CODES = ['_', '-', '|', '+'];

/**
 * grid: Int32Array tile ids; idToCode: tile id -> {shortId} (terrain codes).
 * objects: [{type, subtype, template:{animation, mask}, x, y, l}]
 * header: {width, height, levels, players, ...}
 */
function serializeVmap({ header, tilesByLevel, objects }) {
	const entries = [];

	entries.push({ name: 'header.json', data: JSON.stringify(header, null, 1) });
	for (const [levelName, rows] of Object.entries(tilesByLevel)) {
		entries.push({ name: `${levelName}_terrain.json`, data: JSON.stringify(rows) });
	}
	entries.push({ name: 'objects.json', data: JSON.stringify(objects, null, 1) });

	return writeZip(entries);
}

/**
 * Build a minimal valid header for a generated map.
 * players: [{color, factions:[ids], townPos:{x,y,l}}]
 * levels: [{name:'surface',width,height,index:0}, ...]
 * allFactions: every indexed faction id so "Random" town selection stays
 * legal regardless of what mods add (faction-variable map design).
 */
function makeHeader({ width, height, players, levels, modIds = [], difficulty = 'NORMAL',
	name = 'OmniGen', allFactions = [], declareMods = false, teams = null, allowed = null }) {
	const playerBlock = {};
	for (const p of players) {
		playerBlock[p.color] = {
			allowedFactions: { anyOf: p.factions && p.factions.length ? p.factions : allFactions },
			// PlayerOrAI unless the caller says otherwise. The reader maps the
			// four names in MapFormatJson.cpp's canPlayMap onto the
			// canHumanPlay/canComputerPlay pair, so "AIOnly" is a slot a human
			// cannot take in the lobby and "PlayerOnly" one an AI never gets.
			canPlay: p.canPlay || 'PlayerOrAI',
			mainTown: { generateHero: true, l: p.townPos.l, x: p.townPos.x, y: p.townPos.y },
		};
	}
	const metaText = s => ({ exactStrings: [String(s)], localStrings: null, message: [0], numbers: null, stringsTextID: null });
	const emptyText = { exactStrings: null, localStrings: null, message: null, numbers: null, stringsTextID: null };
	const mapLevels = {};
	(levels || [{ name: 'surface', height, index: 0, width }])
		.forEach(lv => { mapLevels[lv.name] = { height: lv.height, index: lv.index, width: lv.width }; });
	// The mods field records what a map REQUIRES, and the game refuses to load
	// a map whose requirements are not installed. We used to write every mod
	// that happened to be enabled when the map was generated, 68 of them on
	// this machine, which made a map unopenable by anybody whose mod set did
	// not match exactly. That is fatal for sharing a map with anyone.
	//
	// All 71 random maps VCMI's own generator produced on this install declare
	// null, so this now does the same by default. Pass declareMods to opt back
	// in when a map genuinely leans on modded content and should say so.
	//
	// Format note, learned the hard way: entries must be {modId,name,version}
	// objects. The reader calls ["version"].String() on each one, so a plain
	// array of strings crashes at map load.
	const modsList = (declareMods && modIds.length)
		? modIds.map(m => typeof m === 'string'
			? { modId: m, name: m, version: '1.0' }
			: { modId: m.__id, name: m.name || m.__id,
				version: String(m.version || '1.0'),
				// submods name their parent so the loader resolves the pair
				...(m.__parent ? { parent: m.__parent } : {}) })
		: null;
	return {
		versionMajor: 3,
		versionMinor: 0,
		name: metaText(name),
		description: metaText('Generated by OmniMapGen'),
		author: metaText('OmniMapGen'),
		authorContact: emptyText,
		mapVersion: metaText('1.0'),
		difficulty,
		battleOnly: false,
		creationDateTime: Math.floor(Date.now() / 1000),
		mapLevels,
		players: playerBlock,
		// allowedSpells/allowedArtifacts/allowedAbilities/allowedHeroes: an
		// absent list is the engine's full default set; generate.js passes
		// {noneOf, allOf} changes to it (the water and template bans)
		...(allowed || {}),
		victoryIconIndex: 11,
		victoryMessage: { exactStrings: null, localStrings: null, message: [2], numbers: null, stringsTextID: ['core.vcdesc.0'] },
		defeatIconIndex: 3,
		defeatMessage: { exactStrings: null, localStrings: null, message: [2], numbers: null, stringsTextID: ['core.lcdesc.0'] },
		// readTeams wants an array of arrays of player color names;
		// null keeps every player their own team
		teams: teams || null,
		triggeredEvents: {
			standardDefeat: {
				condition: ['daysWithoutTown', { type: '', value: 7 }],
				effect: { messageToSend: emptyText, type: 'defeat' },
				message: { exactStrings: null, localStrings: null, message: [2], numbers: null, stringsTextID: ['core.genrltxt.7'] },
			},
			standardVictory: {
				condition: ['standardWin', { type: '', value: -1 }],
				effect: { messageToSend: emptyText, type: 'victory' },
				message: { exactStrings: null, localStrings: null, message: [2], numbers: null, stringsTextID: ['core.genrltxt.6'] },
			},
		},
		events: [],
		rumors: [],
		mods: modsList,
	};
}

module.exports = { serializeVmap, makeHeader, FLIP_CODES };
